// <auto-generated />
using FirstAidAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FirstAidAPI.Migrations
{
    [DbContext(typeof(FirstAidContext))]
    [Migration("20251007144551_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FirstAidAPI.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("FirstAidAPI.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<int>("TechniqueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("FirstAidAPI.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("FirstAidAPI.Models.Technique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("ScenarioId1")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("ScenarioId1");

                    b.ToTable("Techniques");
                });

            modelBuilder.Entity("FirstAidAPI.Models.TechniqueStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("ExpectedAction")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Instruction")
                        .HasColumnType("text");

                    b.Property<int?>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("TechniqueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("TechniqueId");

                    b.ToTable("TechniqueSteps");
                });

            modelBuilder.Entity("FirstAidAPI.Models.AnswerOption", b =>
                {
                    b.HasOne("FirstAidAPI.Models.QuizQuestion", null)
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FirstAidAPI.Models.Technique", b =>
                {
                    b.HasOne("FirstAidAPI.Models.Scenario", null)
                        .WithMany("Techniques")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FirstAidAPI.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId1");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("FirstAidAPI.Models.TechniqueStep", b =>
                {
                    b.HasOne("FirstAidAPI.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId");

                    b.HasOne("FirstAidAPI.Models.Technique", null)
                        .WithMany("TechniqueSteps")
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("FirstAidAPI.Models.QuizQuestion", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("FirstAidAPI.Models.Scenario", b =>
                {
                    b.Navigation("Techniques");
                });

            modelBuilder.Entity("FirstAidAPI.Models.Technique", b =>
                {
                    b.Navigation("TechniqueSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
