// <auto-generated />
using System;
using FirstAidAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FirstAidAPI.Migrations
{
    [DbContext(typeof(FirstAidContext))]
    [Migration("20251028034158_UpdateForIdentity")]
    partial class UpdateForIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FirstAidAPI.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("FirstAidAPI.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<int>("TechniqueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("FirstAidAPI.Models.SavedTechnique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("TechniqueId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TechniqueId");

                    b.HasIndex("UserId", "TechniqueId")
                        .IsUnique();

                    b.ToTable("SavedTechniques");
                });

            modelBuilder.Entity("FirstAidAPI.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PassingScore")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Xử lý tình huống một người bị ngã xe đạp với vết thương nhẹ. Scenario này phù hợp cho người mới học.",
                            Difficulty = "Dễ",
                            Duration = 10,
                            Icon = "🚴",
                            IsPublished = true,
                            Name = "bicycle-accident",
                            PassingScore = 70,
                            Title = "Tai nạn xe đạp tại công viên",
                            Type = "outdoor"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Xử lý tình huống bị bỏng nhẹ khi đang nấu ăn trong bếp. Học cách sơ cứu bỏng cấp độ 1-2.",
                            Difficulty = "Dễ",
                            Duration = 8,
                            Icon = "🔥",
                            IsPublished = true,
                            Name = "kitchen-burn",
                            PassingScore = 70,
                            Title = "Bỏng nhẹ khi nấu ăn",
                            Type = "home"
                        });
                });

            modelBuilder.Entity("FirstAidAPI.Models.ScenarioAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("UserId", "AttemptedAt");

                    b.ToTable("ScenarioAttempts");
                });

            modelBuilder.Entity("FirstAidAPI.Models.ScenarioStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<string>("StepType")
                        .HasColumnType("text");

                    b.Property<int?>("TechniqueId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("TechniqueId");

                    b.ToTable("ScenarioSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bạn đang đi dạo ở công viên và nhìn thấy một người đi xe đạp bị mất thăng bằng và ngã. Người đó đang nằm trên đường, tỉnh táo nhưng trông có vẻ đau đớn. Bạn nhận thấy đầu gối của họ đang chảy máu.",
                            ImageUrl = "/images/steps/bicycle-fall.jpg",
                            MaxScore = 0,
                            Order = 1,
                            Question = "",
                            ScenarioId = 1,
                            StepType = "information",
                            TimeLimit = 0,
                            Title = "Tình huống ban đầu",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bạn đến gần nạn nhân. Điều đầu tiên bạn cần làm là gì?",
                            ImageUrl = "",
                            MaxScore = 10,
                            Order = 2,
                            Question = "Hành động đầu tiên bạn nên thực hiện là gì?",
                            ScenarioId = 1,
                            StepType = "question",
                            TimeLimit = 30,
                            Title = "Đánh giá ban đầu",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hiện trường đã an toàn. Bạn tiếp cận nạn nhân. Người đó tỉnh táo, đang ngồi dậy và nói 'Đầu gối tôi đau quá'.",
                            ImageUrl = "",
                            MaxScore = 10,
                            Order = 3,
                            Question = "Bước tiếp theo bạn nên làm gì?",
                            ScenarioId = 1,
                            StepType = "question",
                            TimeLimit = 30,
                            Title = "Kiểm tra tình trạng nạn nhân",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bạn đã đeo găng tay. Vết thương ở đầu gối đang chảy máu nhưng không quá nhiều. Có một số vết trầy xước và bụi bẩn.",
                            ImageUrl = "/images/steps/knee-wound.jpg",
                            MaxScore = 15,
                            Order = 4,
                            Question = "Cách xử lý vết thương đúng là gì?",
                            ScenarioId = 1,
                            StepType = "question",
                            TimeLimit = 40,
                            Title = "Xử lý vết thương",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vết thương đã được làm sạch. Máu vẫn còn chảy một chút nhưng đã giảm đáng kể.",
                            ImageUrl = "",
                            MaxScore = 15,
                            Order = 5,
                            Question = "Bạn nên băng bó vết thương như thế nào?",
                            ScenarioId = 1,
                            StepType = "question",
                            TimeLimit = 30,
                            Title = "Băng bó vết thương",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bạn đang nấu ăn trong bếp. Trong lúc vội vàng, bạn vô tình chạm tay vào nồi nóng. Bạn cảm thấy đau rát ở mu bàn tay. Khi nhìn xuống, bạn thấy vùng da bị bỏng đỏ lên và hơi sưng, khoảng bằng đồng xu 500 đồng.",
                            ImageUrl = "/images/steps/hand-burn.jpg",
                            MaxScore = 0,
                            Order = 1,
                            Question = "",
                            ScenarioId = 2,
                            StepType = "information",
                            TimeLimit = 0,
                            Title = "Tình huống",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bạn vừa bị bỏng. Tay đang rất đau và rát.",
                            ImageUrl = "",
                            MaxScore = 15,
                            Order = 2,
                            Question = "Điều đầu tiên bạn cần làm ngay là gì?",
                            ScenarioId = 2,
                            StepType = "question",
                            TimeLimit = 20,
                            Title = "Xử lý ngay lập tức",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 8,
                            Description = "Bạn đang làm mát vết bỏng dưới vòi nước.",
                            ImageUrl = "",
                            MaxScore = 10,
                            Order = 3,
                            Question = "Bạn nên làm mát vết bỏng trong bao lâu?",
                            ScenarioId = 2,
                            StepType = "question",
                            TimeLimit = 30,
                            Title = "Làm mát vết bỏng",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sau khi làm mát 10-15 phút, vết bỏng đã bớt đau. Da vẫn đỏ nhưng không có phồng rộp.",
                            ImageUrl = "",
                            MaxScore = 15,
                            Order = 4,
                            Question = "Bước tiếp theo bạn nên làm gì?",
                            ScenarioId = 2,
                            StepType = "question",
                            TimeLimit = 30,
                            Title = "Xử lý sau khi làm mát",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 10,
                            Description = "Vết bỏng đã được xử lý và băng bó. Tuy nhiên, bạn cần biết khi nào cần đến bác sĩ.",
                            ImageUrl = "",
                            MaxScore = 10,
                            Order = 5,
                            Question = "Trong trường hợp nào bạn NÊN đi khám bác sĩ?",
                            ScenarioId = 2,
                            StepType = "question",
                            TimeLimit = 40,
                            Title = "Đánh giá mức độ nghiêm trọng",
                            VideoUrl = ""
                        });
                });

            modelBuilder.Entity("FirstAidAPI.Models.ScenarioTechnique", b =>
                {
                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<int>("TechniqueId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ScenarioId", "TechniqueId");

                    b.HasIndex("TechniqueId");

                    b.ToTable("ScenarioTechniques");

                    b.HasData(
                        new
                        {
                            ScenarioId = 1,
                            TechniqueId = 1,
                            Order = 1
                        },
                        new
                        {
                            ScenarioId = 1,
                            TechniqueId = 4,
                            Order = 2
                        },
                        new
                        {
                            ScenarioId = 1,
                            TechniqueId = 16,
                            Order = 3
                        },
                        new
                        {
                            ScenarioId = 2,
                            TechniqueId = 2,
                            Order = 1
                        });
                });

            modelBuilder.Entity("FirstAidAPI.Models.StepAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("ScenarioAttemptId")
                        .HasColumnType("integer");

                    b.Property<int>("StepId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("UserAnswer")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioAttemptId");

                    b.HasIndex("StepId");

                    b.ToTable("StepAnswers");
                });

            modelBuilder.Entity("FirstAidAPI.Models.StepOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EndScenario")
                        .HasColumnType("boolean");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackCorrect")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackIncorrect")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int?>("NextStepId")
                        .HasColumnType("integer");

                    b.Property<string>("OptionKey")
                        .HasColumnType("text");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("integer");

                    b.Property<int>("StepId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.ToTable("StepOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndScenario = false,
                            Explanation = "Di chuyển nạn nhân ngay lập tức có thể gây thêm chấn thương nếu có gãy xương hoặc chấn thương nghiêm trọng khác.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Không nên vội vàng. Cần đảm bảo an toàn trước.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "A",
                            ScoreValue = 0,
                            StepId = 2,
                            Text = "Chạy ngay đến bên nạn nhân và đỡ họ đứng dậy"
                        },
                        new
                        {
                            Id = 2,
                            EndScenario = false,
                            Explanation = "Trong mọi tình huống sơ cứu, đảm bảo an toàn hiện trường giúp tránh tai nạn thứ cấp cho cả bạn và nạn nhân.",
                            FeedbackCorrect = "Chính xác! An toàn của bạn và nạn nhân là ưu tiên hàng đầu.",
                            FeedbackIncorrect = "",
                            ImageUrl = "",
                            IsCorrect = true,
                            NextStepId = 3,
                            OptionKey = "B",
                            ScoreValue = 10,
                            StepId = 2,
                            Text = "Đảm bảo an toàn hiện trường (kiểm tra xe cộ xung quanh)"
                        },
                        new
                        {
                            Id = 3,
                            EndScenario = false,
                            Explanation = "Với tai nạn xe đạp nhẹ, nên đánh giá tình huống trước khi gọi cấp cứu. Gọi 115 khi thực sự cần thiết.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Chưa cần thiết. Hãy đánh giá tình huống trước.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "C",
                            ScoreValue = 5,
                            StepId = 2,
                            Text = "Gọi 115 ngay lập tức"
                        },
                        new
                        {
                            Id = 4,
                            EndScenario = false,
                            Explanation = "Sơ cứu nạn nhân luôn là ưu tiên số một. Chụp ảnh có thể làm sau hoặc nhờ người khác.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Ưu tiên là sơ cứu, không phải chụp ảnh.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "D",
                            ScoreValue = 0,
                            StepId = 2,
                            Text = "Chụp ảnh để làm bằng chứng"
                        },
                        new
                        {
                            Id = 5,
                            EndScenario = false,
                            Explanation = "Trước khi xử lý vết thương, bạn cần đeo găng tay để bảo vệ bản thân và tránh nhiễm khuẩn.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Chưa đúng thứ tự. Cần chuẩn bị trước.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "A",
                            ScoreValue = 0,
                            StepId = 3,
                            Text = "Rửa vết thương ngay bằng nước sạch"
                        },
                        new
                        {
                            Id = 6,
                            EndScenario = false,
                            Explanation = "Đeo găng tay giúp tránh tiếp xúc với máu và dịch cơ thể, bảo vệ cả bạn và nạn nhân khỏi nguy cơ nhiễm trùng.",
                            FeedbackCorrect = "Đúng rồi! Bảo vệ bản thân trước khi sơ cứu.",
                            FeedbackIncorrect = "",
                            ImageUrl = "",
                            IsCorrect = true,
                            NextStepId = 4,
                            OptionKey = "B",
                            ScoreValue = 10,
                            StepId = 3,
                            Text = "Đeo găng tay và chuẩn bị dụng cụ sơ cứu"
                        },
                        new
                        {
                            Id = 7,
                            EndScenario = false,
                            Explanation = "Hỏi thông tin là tốt nhưng nên xử lý vết thương trước để tránh nhiễm trùng.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Có thể hỏi nhưng không phải ưu tiên.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "C",
                            ScoreValue = 3,
                            StepId = 3,
                            Text = "Hỏi thông tin cá nhân của nạn nhân"
                        },
                        new
                        {
                            Id = 8,
                            EndScenario = false,
                            Explanation = "Dùng bông khô không loại bỏ được bụi bẩn và vi khuẩn. Cần rửa sạch vết thương bằng nước.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Không nên dùng bông khô. Cần làm sạch trước.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "A",
                            ScoreValue = 0,
                            StepId = 4,
                            Text = "Dùng bông gòn khô để lau máu"
                        },
                        new
                        {
                            Id = 9,
                            EndScenario = false,
                            Explanation = "Rửa bằng nước sạch loại bỏ bụi bẩn và vi khuẩn, giảm nguy cơ nhiễm trùng. Dùng gạc sạch thấm khô tránh làm tổn thương thêm.",
                            FeedbackCorrect = "Xuất sắc! Đây là cách xử lý vết thương đúng chuẩn.",
                            FeedbackIncorrect = "",
                            ImageUrl = "",
                            IsCorrect = true,
                            NextStepId = 5,
                            OptionKey = "B",
                            ScoreValue = 15,
                            StepId = 4,
                            Text = "Rửa nhẹ nhàng bằng nước sạch, sau đó dùng gạc sạch thấm khô"
                        },
                        new
                        {
                            Id = 10,
                            EndScenario = false,
                            Explanation = "Bôi thuốc lên vết thương bẩn có thể nhốt vi khuẩn bên trong, gây nhiễm trùng.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Cần làm sạch vết thương trước khi bôi thuốc.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "C",
                            ScoreValue = 0,
                            StepId = 4,
                            Text = "Thoa thuốc đỏ ngay lên vết thương"
                        },
                        new
                        {
                            Id = 11,
                            EndScenario = false,
                            Explanation = "Hơi thở chứa rất nhiều vi khuẩn. Thổi vào vết thương là cách dễ gây nhiễm trùng nhất.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Tuyệt đối không! Thổi sẽ đưa vi khuẩn vào vết thương.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "D",
                            ScoreValue = 0,
                            StepId = 4,
                            Text = "Thổi vào vết thương để làm sạch"
                        },
                        new
                        {
                            Id = 12,
                            EndScenario = false,
                            Explanation = "Dán băng keo trực tiếp sẽ dính vào vết thương, gây đau và tổn thương khi gỡ ra.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Không tốt. Cần đệm gạc trước.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "A",
                            ScoreValue = 0,
                            StepId = 5,
                            Text = "Dán băng keo trực tiếp lên vết thương"
                        },
                        new
                        {
                            Id = 13,
                            EndScenario = true,
                            Explanation = "Gạc sạch bảo vệ vết thương khỏi nhiễm khuẩn. Băng vừa đủ chặt giúp cầm máu mà không cản trở tuần hoàn.",
                            FeedbackCorrect = "Hoàn hảo! Bạn đã xử lý vết thương rất chuyên nghiệp.",
                            FeedbackIncorrect = "",
                            ImageUrl = "",
                            IsCorrect = true,
                            OptionKey = "B",
                            ScoreValue = 15,
                            StepId = 5,
                            Text = "Đặt gạc sạch lên vết thương, sau đó dùng băng cuộn cố định (không quá chặt)"
                        },
                        new
                        {
                            Id = 14,
                            EndScenario = false,
                            Explanation = "Băng quá chặt có thể cản trở lưu thông máu, gây tê và tổn thương mô. Băng vừa đủ là được.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Băng quá chặt có thể gây nguy hiểm.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "C",
                            ScoreValue = 5,
                            StepId = 5,
                            Text = "Băng rất chặt để cầm máu nhanh"
                        },
                        new
                        {
                            Id = 15,
                            EndScenario = false,
                            Explanation = "Để vết thương hở dễ bị nhiễm khuẩn từ môi trường. Luôn băng bó để bảo vệ vết thương.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Không an toàn. Vết thương cần được che phủ.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "D",
                            ScoreValue = 0,
                            StepId = 5,
                            Text = "Để vết thương hở thoáng khí"
                        },
                        new
                        {
                            Id = 16,
                            EndScenario = false,
                            Explanation = "Đá lạnh quá có thể làm tổn thương mô da đang bị bỏng. Nên dùng nước mát (15-20°C).",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Không nên dùng đá trực tiếp! Có thể gây tổn thương thêm.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "A",
                            ScoreValue = 0,
                            StepId = 7,
                            Text = "Chạy ngay đến tủ lạnh lấy đá chườm"
                        },
                        new
                        {
                            Id = 17,
                            EndScenario = false,
                            Explanation = "Làm mát vết bỏng ngay lập tức giúp giảm đau, giảm sưng và hạn chế tổn thương sâu hơn vào da.",
                            FeedbackCorrect = "Chính xác! Đây là cách xử lý bỏng đúng nhất.",
                            FeedbackIncorrect = "",
                            ImageUrl = "",
                            IsCorrect = true,
                            NextStepId = 8,
                            OptionKey = "B",
                            ScoreValue = 15,
                            StepId = 7,
                            Text = "Ngâm vết bỏng vào nước mát (không quá lạnh) hoặc để dưới vòi nước chảy"
                        },
                        new
                        {
                            Id = 18,
                            EndScenario = false,
                            Explanation = "Kem đánh răng, dầu ăn, bơ... không phải là thuốc trị bỏng và có thể gây nhiễm trùng nghiêm trọng.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Không đúng! Kem đánh răng có thể gây nhiễm trùng.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "C",
                            ScoreValue = 0,
                            StepId = 7,
                            Text = "Bôi kem đánh răng lên vết bỏng"
                        },
                        new
                        {
                            Id = 19,
                            EndScenario = false,
                            Explanation = "Băng bó ngay sẽ giữ nhiệt bên trong, làm vết bỏng nghiêm trọng hơn. Luôn làm mát trước.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Chưa đúng. Cần làm mát trước khi băng bó.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "D",
                            ScoreValue = 0,
                            StepId = 7,
                            Text = "Băng bó ngay lập tức"
                        },
                        new
                        {
                            Id = 20,
                            EndScenario = false,
                            Explanation = "2-3 phút quá ngắn để giảm nhiệt độ ở sâu bên trong da.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Chưa đủ thời gian. Cần làm mát lâu hơn.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "A",
                            ScoreValue = 3,
                            StepId = 8,
                            Text = "2-3 phút là đủ"
                        },
                        new
                        {
                            Id = 21,
                            EndScenario = false,
                            Explanation = "10-15 phút là thời gian đủ để làm mát vết bỏng hiệu quả, giảm tổn thương và đau.",
                            FeedbackCorrect = "Đúng rồi! Đây là thời gian khuyến cáo.",
                            FeedbackIncorrect = "",
                            ImageUrl = "",
                            IsCorrect = true,
                            NextStepId = 9,
                            OptionKey = "B",
                            ScoreValue = 10,
                            StepId = 8,
                            Text = "10-15 phút"
                        },
                        new
                        {
                            Id = 22,
                            EndScenario = false,
                            Explanation = "Với bỏng nhẹ, 10-15 phút là đủ. Quá lâu có thể gây hạ thân nhiệt.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Quá lâu và không cần thiết với bỏng nhẹ.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "C",
                            ScoreValue = 5,
                            StepId = 8,
                            Text = "30 phút đến 1 giờ"
                        },
                        new
                        {
                            Id = 23,
                            EndScenario = false,
                            Explanation = "Phồng rộp là lớp bảo vệ tự nhiên. Chọc vỡ sẽ làm tăng nguy cơ nhiễm trùng.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Tuyệt đối không! Có thể gây nhiễm trùng.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "A",
                            ScoreValue = 0,
                            StepId = 9,
                            Text = "Chọc vỡ phồng rộp (nếu có) để dẫn lưu"
                        },
                        new
                        {
                            Id = 24,
                            EndScenario = false,
                            Explanation = "Thuốc bỏng hoặc gel lô hội giúp làm dịu và tăng tốc quá trình lành vết thương. Băng bó nhẹ bảo vệ vết bỏng.",
                            FeedbackCorrect = "Xuất sắc! Đây là cách xử lý bỏng đúng chuẩn.",
                            FeedbackIncorrect = "",
                            ImageUrl = "",
                            IsCorrect = true,
                            NextStepId = 10,
                            OptionKey = "B",
                            ScoreValue = 15,
                            StepId = 9,
                            Text = "Thoa thuốc bỏng (nếu có) hoặc gel lô hội, sau đó băng bó nhẹ nhàng"
                        },
                        new
                        {
                            Id = 25,
                            EndScenario = false,
                            Explanation = "Dầu, mỡ, bơ sẽ giữ nhiệt bên trong, làm vết bỏng nghiêm trọng hơn và dễ nhiễm trùng.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Sai hoàn toàn! Dầu mỡ giữ nhiệt và gây nhiễm trùng.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "C",
                            ScoreValue = 0,
                            StepId = 9,
                            Text = "Bôi dầu ăn hoặc mỡ lên vết bỏng"
                        },
                        new
                        {
                            Id = 26,
                            EndScenario = false,
                            Explanation = "Bỏng nhẹ, nhỏ không có phồng rộp thường tự lành sau vài ngày với chăm sóc đúng cách tại nhà.",
                            FeedbackCorrect = "",
                            FeedbackIncorrect = "Trường hợp này có thể tự xử lý tại nhà.",
                            ImageUrl = "",
                            IsCorrect = false,
                            OptionKey = "A",
                            ScoreValue = 5,
                            StepId = 10,
                            Text = "Vết bỏng chỉ bằng đồng xu, đỏ nhẹ, không phồng rộp"
                        },
                        new
                        {
                            Id = 27,
                            EndScenario = true,
                            Explanation = "Vết bỏng lớn hoặc có nhiều phồng rộp cần được bác sĩ đánh giá và xử lý chuyên nghiệp để tránh biến chứng.",
                            FeedbackCorrect = "Đúng rồi! Trường hợp này cần gặp bác sĩ.",
                            FeedbackIncorrect = "",
                            ImageUrl = "",
                            IsCorrect = true,
                            OptionKey = "B",
                            ScoreValue = 10,
                            StepId = 10,
                            Text = "Vết bỏng lớn hơn lòng bàn tay hoặc có nhiều phồng rộp"
                        },
                        new
                        {
                            Id = 28,
                            EndScenario = true,
                            Explanation = "Bỏng ở các vùng này có thể gây biến chứng nghiêm trọng về thẩm mỹ và chức năng, cần điều trị chuyên khoa.",
                            FeedbackCorrect = "Chính xác! Vùng này rất nhạy cảm, cần bác sĩ.",
                            FeedbackIncorrect = "",
                            ImageUrl = "",
                            IsCorrect = true,
                            OptionKey = "C",
                            ScoreValue = 10,
                            StepId = 10,
                            Text = "Vết bỏng ở mặt, tay, chân, hoặc bộ phận sinh dục"
                        },
                        new
                        {
                            Id = 29,
                            EndScenario = true,
                            Explanation = "Vết bỏng lớn, nhiều phồng rộp, hoặc ở vùng nhạy cảm đều cần được bác sĩ khám và điều trị.",
                            FeedbackCorrect = "Hoàn hảo! Bạn đã hiểu rõ khi nào cần đến bác sĩ.",
                            FeedbackIncorrect = "",
                            ImageUrl = "",
                            IsCorrect = true,
                            OptionKey = "D",
                            ScoreValue = 10,
                            StepId = 10,
                            Text = "Cả B và C đều đúng"
                        });
                });

            modelBuilder.Entity("FirstAidAPI.Models.Technique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Techniques");
                });

            modelBuilder.Entity("FirstAidAPI.Models.TechniqueStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("ExpectedAction")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Instruction")
                        .HasColumnType("text");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("TechniqueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TechniqueId");

                    b.ToTable("TechniqueSteps");
                });

            modelBuilder.Entity("FirstAidAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FirstAidAPI.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AchievementType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AchievementType")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("FirstAidAPI.Models.UserScenarioProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HighestScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("LastAccessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("UserId", "ScenarioId")
                        .IsUnique();

                    b.ToTable("UserScenarioProgresses");
                });

            modelBuilder.Entity("FirstAidAPI.Models.UserTechniqueProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsVideoWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastAccessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("TechniqueId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TechniqueId");

                    b.HasIndex("UserId", "TechniqueId")
                        .IsUnique();

                    b.ToTable("UserTechniqueProgresses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FirstAidAPI.Models.AnswerOption", b =>
                {
                    b.HasOne("FirstAidAPI.Models.QuizQuestion", null)
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FirstAidAPI.Models.SavedTechnique", b =>
                {
                    b.HasOne("FirstAidAPI.Models.Technique", "Technique")
                        .WithMany()
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstAidAPI.Models.User", "User")
                        .WithMany("SavedTechniques")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technique");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FirstAidAPI.Models.ScenarioAttempt", b =>
                {
                    b.HasOne("FirstAidAPI.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstAidAPI.Models.User", "User")
                        .WithMany("ScenarioAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FirstAidAPI.Models.ScenarioStep", b =>
                {
                    b.HasOne("FirstAidAPI.Models.Scenario", "Scenario")
                        .WithMany("ScenarioSteps")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstAidAPI.Models.Technique", "Technique")
                        .WithMany()
                        .HasForeignKey("TechniqueId");

                    b.Navigation("Scenario");

                    b.Navigation("Technique");
                });

            modelBuilder.Entity("FirstAidAPI.Models.ScenarioTechnique", b =>
                {
                    b.HasOne("FirstAidAPI.Models.Scenario", "Scenario")
                        .WithMany("ScenarioTechniques")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstAidAPI.Models.Technique", "Technique")
                        .WithMany("ScenarioTechniques")
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("Technique");
                });

            modelBuilder.Entity("FirstAidAPI.Models.StepAnswer", b =>
                {
                    b.HasOne("FirstAidAPI.Models.ScenarioAttempt", "ScenarioAttempt")
                        .WithMany("StepAnswers")
                        .HasForeignKey("ScenarioAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstAidAPI.Models.ScenarioStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScenarioAttempt");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("FirstAidAPI.Models.StepOption", b =>
                {
                    b.HasOne("FirstAidAPI.Models.ScenarioStep", "Step")
                        .WithMany("Options")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("FirstAidAPI.Models.TechniqueStep", b =>
                {
                    b.HasOne("FirstAidAPI.Models.Technique", "Technique")
                        .WithMany("TechniqueSteps")
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Technique");
                });

            modelBuilder.Entity("FirstAidAPI.Models.UserAchievement", b =>
                {
                    b.HasOne("FirstAidAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FirstAidAPI.Models.UserScenarioProgress", b =>
                {
                    b.HasOne("FirstAidAPI.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstAidAPI.Models.User", "User")
                        .WithMany("ScenarioProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FirstAidAPI.Models.UserTechniqueProgress", b =>
                {
                    b.HasOne("FirstAidAPI.Models.Technique", "Technique")
                        .WithMany()
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstAidAPI.Models.User", "User")
                        .WithMany("TechniqueProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technique");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FirstAidAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FirstAidAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstAidAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FirstAidAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FirstAidAPI.Models.QuizQuestion", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("FirstAidAPI.Models.Scenario", b =>
                {
                    b.Navigation("ScenarioSteps");

                    b.Navigation("ScenarioTechniques");
                });

            modelBuilder.Entity("FirstAidAPI.Models.ScenarioAttempt", b =>
                {
                    b.Navigation("StepAnswers");
                });

            modelBuilder.Entity("FirstAidAPI.Models.ScenarioStep", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("FirstAidAPI.Models.Technique", b =>
                {
                    b.Navigation("ScenarioTechniques");

                    b.Navigation("TechniqueSteps");
                });

            modelBuilder.Entity("FirstAidAPI.Models.User", b =>
                {
                    b.Navigation("SavedTechniques");

                    b.Navigation("ScenarioAttempts");

                    b.Navigation("ScenarioProgresses");

                    b.Navigation("TechniqueProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
